### ISSUE TITLE
PCORnet indexes

### ISSUE THREAD

**Issue by burrowse** [PEDSnet/pedsnetcdm_to_pcornetcdm#108]
Moving Issue From Data Models Repo [Issue](https://github.com/PEDSnet/Data_Models/issues/254):

Original comment:
"Looks like PCORnet spec doesn't address indexes; marker for thinking about logical index choices."

From: https://github.research.chop.edu/dbhi/pedsnet/issues/98#issue-3430

**Comment by writetoritu** [comment]
Also update the FKs
