### ISSUE TITLE
NDC constraint in PCORnet CDM spec

### ISSUE THREAD

**Issue by baileych** [PEDSnet/pedsnetcdm_to_pcornetcdm#118]
The PCORnet CDM specifies that NDC codes in `dispensing` *must* be 11-digit codes.  PEDSnet has a small subset (~29,000) records with 10-digit NDC codes from the source data; we need to redact these records when building the PCORnet CDM.

**Comment by toanong** [comment]
I found this page talking about the conversion:

http://www.michigan.gov/documents/lara/lara_MAPS_NDC_Guidelines_396516_7.pdf

Are all of these 29K records following the three different formats: 4-4-2, 3-5-2, and 5-4-1?

**Comment by mgkahn** [comment]
I went down this rabbit hole of trying to correctly parse 10-digit NDC codes with the three allowed formats with Jerry Pulver from Family Medicine and eventually gave up. These are old outdated NDC codes (all are now 11 digits). I would not advocate for trying this exercise again.

**Comment by ErezYehuda** [comment]
Ritu and I were unable to find any NDC codes that did not match the 11-digit format. We tested it with the query `select * from dcc_pcornet.dispensing where ndc !~* '\d{11}'` on DB01, pedsnet_dcc_v23.

**Comment by writetoritu** [comment]
@ErezYehuda So we just need to add a clause in the subquery `concept_class_id='11-digit NDC'`
