### ISSUE TITLE
create a table with start-2001 patients and encounters 

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#131]

**Comment by piglet25** [comment]
Table created using the following SQL pushed to the start2001 branch in the start2001 folder in file named create_patient_visit_start2001.sql.

CREATE TABLE chop_start2001_pcornet.person_visit_start2001 
AS
SELECT person_id, visit_occurrence_id AS visit_id
FROM chop_pedsnet.visit_occurrence
WHERE EXTRACT(YEAR FROM visit_start_date) >= 2001;
