### ISSUE TITLE
mismatch between #records between source/target CHOP (overall) testing

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#134]
- observation_period vs. enrollment 
- death (should be 2657?) 
- death_cause has no records? 
- visit_occurrene- >encounter
- for other tables, we are seeing fewer than expected records (Although they are not supposed to perfectly match with the source table ).

**Comment by ErezYehuda** [comment]
Discrepancies in source/destination counts were due to the source data being updated.
