### ISSUE TITLE
ETL for Vital.vital_source

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#16]
The prescribed values include: 
PR=Patient-reported
PD=Patient device direct feed
HC=Healthcare delivery setting
HD=Healthcare device direct feed
NI=No information
UN=Unknown
OT=Other

... need to look at what the sites currently have in their observation/measurement tables (measurement_type_concept_id, etc) and derive mappings to PCORnet. 

The current code for Vital ETL is incomplete.

**Comment by writetoritu** [comment]
Values used by various sites 
- Measurement type concept id
    - Lab result (44818702) 
    - From physical examination or vital sign (44818701)  

- Observation type concept id 
    - observation recorded from the EHR (38000280)

For PEDSnet CDM 2.1, we allow the following values 
Measurement type concept id 
- Vital Sign= 44818701
- Lab result = 44818702
- Pathology finding = 44818703
- Patient reported value = 44818704
- Derived Value = 45754907

Observation type concept id : FOR PEDSnet CDM v2.1, we use concept_id = 38000280 (observation recorded from EMR). When we get data from patients, we will include the concept_id = 44814721 (patient reported)

**Comment by burrowse** [comment]
Need to investigate:
Can sites make this distinction between the values?
HC=Healthcare delivery setting
HD=Healthcare device direct feed

**Comment by writetoritu** [comment]
Just confirming that 
- As of now, we will default vital.vital_source to 'HC' 
- In the meanwhile, we will ask the sites whether they can differentiate between HC and HD and will make any applicable changes to PEDSnet conventions 2.1

Is that correct @toanong ?

**Comment by toanong** [comment]
That is correct.

**Comment by burrowse** [comment]
Sites can distinguish between hc and hd... do we need to make concepts to specifically define these options and change the convention?

**Comment by burrowse** [comment]
The conventions have been updated to include specific concepts for HC and HD for the vitals
