### ISSUE TITLE
Vital Table Query Fails to Complete

### ISSUE THREAD

**Issue by piglet25** [PEDSnet/pedsnetcdm_to_pcornetcdm#165]
vital failed with this error: ERROR:  numeric field overflow                                                            
DETAIL:  A field with precision 15, scale 8 must round to an absolute value less than 10^7.

**Comment by writetoritu** [comment]
New problem ERROR:  could not write to hash-join temporary file: No space left on device

**Comment by writetoritu** [comment]
Run VACUUM ANALYZE on source tables.
