### ISSUE TITLE
Code Review PEDSnet v2.5->PEDSnet v3.1 scripts

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#170]
Please review the code in [the v2.5 to v3.1 folder](https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/tree/master/v2.5_to_v3.1).
Please add any code review comments on this issue. 
Also, most of these tables are populated on the 01 server (`dcc_3dot1*` schemas) in case you want to query them. We track the publishing of those tables in #180 

We will use the following table to keep track of code review status. 

| Table | main script | start2001 script |
| --- | --- | --- |
| Demographic | | |
| Enrollment | | |
| Death |  |  | 
| Death Cause |  |  |   
| Encounter |  |  | 
| Condition |  |  | 
| Diagnosis |  |  |   
| Procedures |  |  | 
| Dispensing |  |  |  
| Prescribing |  |  | 
| Vital |  |  |  
| Lab Result CM |  |  |

**Comment by razzaghih** [comment]
The columns in the Excel document for pedsnet --> pcornet mappings do not match the table that you create (cz_omop_pcornet_concept_map_ddl.sql). It's not a big deal but can be confusing.

**Comment by razzaghih** [comment]
In the demographic table, I didn't see columns for sexual orientation, gender identity, raw_sexual_orientation, and raw_gender_identity. It must be in the DDL somewhere but I didn't see it in your scripts.

**Comment by razzaghih** [comment]
In the demographic table, why is it looking at gender_source_concept_id? There doesn't seem to be a mapping for it in the mapping table.

**Comment by razzaghih** [comment]
The values for Race in the Excel document are not accepted values in our gender_concept_id field in the pedsnet person table. It doesn't hurt to include them- I think they are in Observation table.

**Comment by razzaghih** [comment]
In the Demographic table, you have: cast(p.person_id as text) as pat_id... should this be patid?

**Comment by razzaghih** [comment]
In the Death table, I'm not sure why you are joining to the demographic table for patid. Can you instead join to the person_id from the death table in PEDSnet?

**Comment by razzaghih** [comment]
In the Death table - why are you taking the min(site) and then doing a group by? Would there be an instance where there are multiple sites are given?

**Comment by razzaghih** [comment]
In the Encounter table, you are taking the H:M from the visit_start_date and visit_end_date fields and not the visit_start_time and visit_end_time fields.

**Comment by razzaghih** [comment]
The Adult Foster Home value in PCORnet (AF) is being mapped to concept_id = 38004205, which is just Foster Care Agency. I know it's the best mapping available but it's not entirely accurate since I don't think we can assume Adult in our population. However, I don't know that there is a better alternative.

**Comment by razzaghih** [comment]
In the Encounter table - the distcharge_status in our observation table is being mapped from value_as_concept_id = 44814701 (which is what we have values for). In the mappings document, you don't have this code and you have it mapping from concept_id = 44814680.

**Comment by razzaghih** [comment]
In the Encounter table, for the admitting source (observation_concept_id = 4145666), in our Observation table, home health is being mapped to 44814674. In the Excel spreadsheet, it is being mapped to 38004195, which produces 0 rows in the Observation table.

**Comment by razzaghih** [comment]
In the Encounter table: Admitting Source concept id (observation_concept_id = 4145666) has a mapping from value_as_concept_id = 44814675 that is currently not being captured in the crosswalk spreadsheet (590,266 total rows).

**Comment by razzaghih** [comment]
In the Encounter table: there is no mapping from 'Ambulatory Health care facilities, clinic/center' - the value_as_concept_id  = 38004207. This value is not in the crosswalk.

**Comment by razzaghih** [comment]
Should we constrain the admitting source, discharge status, discharge disposition to only 9201 and 2000000048 visits - instead of including all visits except AV and OA?

**Comment by razzaghih** [comment]
In the Encounter table: providerid (PCORnet) is supposed to be character but provider_id is integer in PEDSnet... should there be a cast? Similarly for facilityid (PCORnet) mapping from care_site_id.

**Comment by razzaghih** [comment]
In the Encounter table: the statement:

`left join dcc_3dot1_pcornet.cz_omop_pcornet_concept_map m1 on case when v.visit_concept_id is null AND m1.source_concept_id is null then true else 	cast(v.visit_concept_id as text)= m1.source_concept_id end and m1.source_concept_class='Encounter type'
`
Will visit_concept_id ever be null?

**Comment by razzaghih** [comment]
In the Encounter table: Why is there a group by visit_concept_id and not raw_source_value or site?
