### ISSUE TITLE
adult foster care mapping 

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#199]
The Adult Foster Home value in PCORnet (AF) is being mapped to concept_id = 38004205, which is just Foster Care Agency. I know it's the best mapping available but it's not entirely accurate since I don't think we can assume Adult in our population. However, I don't know that there is a better alternative.

**Comment by writetoritu** [comment]
@baileych thoughts?

**Comment by baileych** [comment]
@writetoritu This was likely assigned as the best available match at the time.  But we now have a concept in the dedicated PCORnet vocabulary for Adult Foster Care.  We'd need to update the ETL conventions to account for this, though.  @burrowse ?

**Comment by writetoritu** [comment]
@baileych I think the ETL convention reflects the correct concept 44814670 for admitting source but points to 38004205 for discharge disposition. @burrowse  thoughts?

**Comment by burrowse** [comment]
@baileych @writetoritu I am not sure when the disconnect happened. 

Based on the vocabulary it appears that 44814670 is correct for admitting source but we should have 44814690 for the discharge destination.

 select * from concept where vocabulary_id='PCORNet' and concept_class_id ~ 'Discharge Status';

We will need to align the conventions for the concepts created for the PCORnet admitting source and discharge status. I'm not sure if this can fit in v2.6 as it could potentially some ETL changes.
