### ISSUE TITLE
condition_source_value

### ISSUE THREAD

**Issue by razzaghih** [PEDSnet/pedsnetcdm_to_pcornetcdm#208]
In the Conditions table, the code is doing this:

`case when c2.vocabulary_id in ('ICD9CM', 'ICD10','ICD10CM') 
		then 
		c2.concept_code
		else case when co.condition_concept_id>0
		 then c1.concept_code 
		 else case when condition_source_Value  like '%|%' then trim(split_part(condition_source_value,'|',2))
				else  trim(condition_source_value)  end  end end `

My understanding is that it first looks for the condition_source_concept_id to map to the ICD9/ICD10 value. This should do the trick for almost all the sites. 

Seattle, however, sometimes uses ICD and sometimes uses SNOMED codes here. Among other sites, there is some inconsistency between ICD9 and ICD10.

The problem of looking into condition_source_value then is that sites are coding that field consistently. Here is what it looks like:

CHOP: name|code
Colorado: name|code
Seattle: SNOMED code only
St. Louis: |term name (when available)|ICD code
Nationwide: name|code
Nemours: name|code

The way you have it will work for the vast majority of our conditions, given that the proportion of conditions that won't be caught using the code you have is small (I believe we only wouldn't get Seattle).

**Comment by writetoritu** [comment]
@razzaghih for Seattle it will just push `trim(condition_source_value)` as it wont pass the ` condition_source_Value like '%|%'` test

Does that look right?

**Comment by razzaghih** [comment]
yes, that makes sense. So it will just assign SNOMED or ICD where applicable. We just won't be getting ICD from them consistently.

**Comment by writetoritu** [comment]
if we do fallback to condition_source_value  (when both concept_id and source_concept_id are 0) then we code the vocabulary as OT as we cant tell whether its ICD or SNOMED

**Comment by razzaghih** [comment]
Also, do we first want the code to look in condition_source_value before condition_concept_id since we want to exhaust our ICD options prior to looking in SNOMED?

**Comment by writetoritu** [comment]
We assume that If there is a valid ICD code then it will be captured in condition_source_concept_id. Hence, we look into condition_concept_id before resorting to condition_source_Value

**Comment by razzaghih** [comment]
Right - just asking if we want to fall back to looking in this order to ensure that we get ICD, in the event that it's missing from condition_source_concept_id:
1) looking at condition_source_concept_id
2) looking at condition_source_value
3) falling back to snomed in condition_concept_id

The way we have it now will work - I am just suggesting a backup if we want to ensure that ICD is captured. I'm fine either way!

**Comment by writetoritu** [comment]
The only issue with `looking at condition_source_value` is that we dont know the correct vocabulary for it -  09, 10, or SM.
