### ISSUE TITLE
raw_condition_source

### ISSUE THREAD

**Issue by razzaghih** [PEDSnet/pedsnetcdm_to_pcornetcdm#210]
In the Condition table - 
`co.condition_source_value as raw_condition,`

If we eventually want to have sites send us local codes (which can be IMO), I don't think we should send the condition_source_value to them as it could lead to some issues. How do you feel about putting our SNOMED code in there?

**Comment by writetoritu** [comment]
good point! 
For v2.6, we will need to discuss with @baileych - which component of `condition_source_value` would go into the `raw_condition` field.

**Comment by baileych** [comment]
Good point - ditto for `raw_dx`.  I think it's reasonable to forward the ICD code, and probably the text term - not a privacy or licensing consideration, but not sure exactly what PCORnet had in mind.

**Comment by razzaghih** [comment]
We are forwarding the ICD code for dx... are you suggesting we duplicate it in the raw_dx field?

**Comment by writetoritu** [comment]
@ChavanShweta Please change the diagnosis and condition queries: 

 - split_part(condition_source_value,'|',3) as raw_dx
 -  split_part(condition_source_value,'|',3) as raw_condition
