### ISSUE TITLE
populating prescribing table

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#25]
- [ ] rx_order_date and rx_order_time: order date is not available in PEDSnet CDM. Use drug_exposure start date instead? 
    - rx_order_date = Order date of the prescription by the provider.
    - rx_order_time = Order time of the prescription by the provider.

- [ ] rx_frequency: do we need to convert effective dose to rx_frequency ?  
    - definition: Specified frequency of medication. 
    - predefined values = 01=Every day 02=Two times a day (BID) 03=Three times a day (TID) 04=Four times a day (QID) 05=Every morning 06=Every afternoon 07=Before meals 08=After meals 09=As needed (PRN) NI=No information UN=Unknown

**Comment by toanong** [comment]
Concept Name             Concept ID                 Vocabulary
Every day                     45881677                   LOINC
2 times per day            45883167                   LOINC
3 times per day            45883169                   LOINC
4 times per day            45882529                   LOINC
Every morning              4141102                    SNOMED
Every afternoon            [missing]                    [missing]
Before meal [singular]  4145729                     SNOMED
With or after meal         4208952                    SNOMED
As needed                    45881909                  LOINC

**Comment by toanong** [comment]
Drug_exposure -> Prescribing where drug_type_concept_id IN ('38000180','38000177') 
-- 38000180 = Inpatient administration, 38000177 = Prescription written

**Comment by writetoritu** [comment]
Prescribing 
- order date and order time 
    - use drug exposure start date and end date == yes 
    - in query, don’t put inpatient admin in prescribing table. (still keep them in PEDSnet)   

- rx frequency --- keeping it null for now until we have a method to extract from sig field (or new convention in PEDSnet)
