### ISSUE TITLE
populating death table 

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#27]
death_date_impute:  No for now, where to store this information in PEDSnet CDM?

- When date of death is imputed, this field indicates which parts of the date were imputed.
- acceptable values : B=Both month and day imputed D=Day imputed M=Month imputed N=Not imputed NI=No information UN=Unknown OT=Other

**Comment by toanong** [comment]
Review the decision for:
death_source
death_match_confidence

**Comment by writetoritu** [comment]
death date impute: ‘NI’ — default for now until next ETL cycle
