### ISSUE TITLE
revise mapping for pdx

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#315]
Please add the following new mappings

P	pdx	38000199	NULL	Principal
P	pdx	38000230	NULL	Principal
S	pdx	38000201	NULL	Secondary 
S	pdx	38000231	NULL	Secondary

**Comment by ChavanShweta** [comment]
PDX  | X=Unable to Classify is deprecated by PCORnet. Change the pdx mapping:

https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/079bb74bb99dde24e47d0726fac46796890da7ba/v3.1_to_v4.1/sql_etl/scripts/etl_scripts/h_diagnosis.sql#L38

**Comment by ChavanShweta** [comment]
Accommodate following data model changes:

Visit_concept_id | Condition_type_concept_id
-- | --
9201 (Inpatient) | Inpatient header
9202 (Outpatient) | Outpatient header
9203 (Emergency) | Emergency header
2000000048 (ED to Inpatient) | Inpatient header
2000000088 (Observation) | Inpatient header

Note: For sites that are splitting the ED to Inpatient) encounters into 1 "9203- Emergency" visit and 1 "9201- Inpatient" visit, not using the "2000000048- ED to Inpatient" visit type, apply diagnosis values from the inpatient setting to the "9203-Emergency visit" with an inpatient condition_type_concept_id.

Concept_id | Concept_Name | Concept_class_id | Domain_id
-- | -- | -- | --
2000001280 | Emergency Header - 1st Position - Order Origin | Condition Type | Type Concept
2000001281 | Emergency Header - 1st Position - Claim Origin | Condition Type | Type Concept
2000001282 | Emergency Header - 1st Position - Billing Origin | Condition Type | Type Concept
2000001283 | Emergency Header - 2nd Position - Order Origin | Condition Type | Type Concept
2000001284 | Emergency Header - 2nd Position - Claim Origin | Condition Type | Type Concept
2000001285 | Emergency Header - 2nd Position - Billing Origin | Condition Type | Type Concept
