### ISSUE TITLE
Test tobacco mappings on Vital query

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#33]

**Comment by writetoritu** [comment]
@toanong I don’t see any ‘smoking’ mapping in the latest file that you had sent me (Sep 2 version). There are only tobacco and tobacco type concept classes. 

Also, we need to insert ETL logic for smoking, tobacco and tobacco type in the vital query to be able to test these updated tobacco tables

**Comment by toanong** [comment]
The mappings for TOBACCO was not finalized because the logic for smoking, tobacco and tobacco type was not finalized. We should have a discussion on today's call about how (and who) best to define this logic.

**Comment by burrowse** [comment]
Updates to the convention document:

TODO: 
- Snapshot Vocabulary, Generate concept for Not Asked if not there
- Use the national snomed code for the occasional tobacco smoker
- Replace 40765262	PhenX-environmental exposures- current environmental tobacco smoke exposure protocol) with  4030580 — (second hand smoke exposure)
- Tobacco relationship concept id  put a 0

**Comment by burrowse** [comment]
@toanong Can you confirm the international snomed code for occasional tobacco smoker?

**Comment by burrowse** [comment]
Commit for the above changes EKB(9/24/15) [here] (https://github.com/PEDSnet/Data_Models/commit/4d45ccb91739d96db0fa2fa80590aaaf30f5f2f3).

**Comment by toanong** [comment]
Here it is: 428041000124106

**Comment by burrowse** [comment]
Thanks @toanong. It appears the 428041000124106 code does not exist in the OMOP vocabulary (at least for the current version). Need to confirm this with a more recent snapshot

**Comment by toanong** [comment]
According to Rimma, this is an international SNOMED code (not sure where they found it) so it didn't surprise me if you couldn't find it in the OMOP vocabulary. We might just treat it as a custom code.
