### ISSUE TITLE
Self-reported health conditions and diseases

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#38]
Question for @baileych et al. 

Do we capture self reported health conditions and diseases (different from PROs) in EMRs?

This question came up as we were discussing what goes into the PCORnet.CONDITION table other than the problem list entry.

**Comment by mgkahn** [comment]
@baileych can answer for CHOP but I do know that some sites (not Colorado) use the EPIC patient portal (MyChart) to push patient self reported health conditions into their EHR. We (Colorado) do not do this using MyChart or any other method to gather this information from patients into the EHR. But I suggest querying all of the sites to see if others use their EHR-based patient portals to obtain this type of information.
