### ISSUE TITLE
Lab_result_cm.lab_order_date and result_date

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#40]
PCORnet asks for three dates: 
- lab order date: Date test was ordered.
- specimen date: Date specimen was collected.
- result date: Result date.  (required field)

In PEDSnet, we only have measurement_date (The date of the measurement.) 

We need to decide how to populate the 3 fields and whether to expand pedsnet to accommodate other two dates?

**Comment by burrowse** [comment]
Sites Investigation:
Measurement Date - Need to determine how this date is being populated by the site? 
Today : populate all dates using the measurement date (only date that we have at the moment)
Version 2.1:
Add order date into the table
Add fact relationship link for procedure and components (Order Date - can be derived from procedure)
Add specimen date
Convention populate the Measurement Date with the Result Date from the EHR

**Comment by burrowse** [comment]
@writetoritu This issue can be closed.
