### ISSUE TITLE
Lab result - range and modifiers

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#41]
1. norm_range_low/high: TODO: incorporate the solution for non-numeric range values (Michael Kahn has some use cases) 
    - option 1: link measurement to observation table 
    - option 2: add two columns to pedsnet cdm - range low source value. 
2. norm_modifier_low and norm_modifier_high (this is specific to range): No place for this in PEDSNet CDM. Link to observation maybe?
    - default for low = GE
    - default for high = LE

**Comment by mgkahn** [comment]
I vote for #2. This is how the OMOP CDM model evolves over iterations. We can use all of our instances of where we needed to modify the CDM as use cases/arguments for changes in OMOP CDM V6. Each iteration in the CDM has been based on real from-the-field needs.

It is always my preference to change the model if that makes more sense than fold, spindle (never really understood that word), mutilate, contort a concept to make it fit into the constraints of the current model. It makes much more sense to me to expand the Measurement table for new attributes related to measurements than to stick them into observations and link with face-relation.

I have the same asthma about some of the gyrations that the national OMOP-PCORnet modeling group is doing over tobacco, tobacco status, tobacco type, tobacco sauce (oops, that's Tobasco.....).

**Comment by burrowse** [comment]
The addition of the two columns (#2) range_high_source_value and range_low_source_value has been implemented as a Pedsnet v2.1.0 change

**Comment by burrowse** [comment]
Will need to add range high and range low modifiers

**Comment by burrowse** [comment]
@toanong @writetoritu Can you provide some information on what kind of information will be stored in the modifier columns?

**Comment by writetoritu** [comment]
The norm_modifier_low and norm_modifier_high fields are associated with the norm_range_low and norm_range_high fields resp. 

- NORM_MODIFIER_LOW: 
    - acceptable values: EQ=Equal, GE=Greater than or equal to, GT=Greater than, NO=No lower limit, NI=No information, UN=Unknown, OT=Other

- NORM_MODIFIER_HIGH: 
    - acceptable values: EQ=Equal, LE=Less than or equal to, LT=Less than, NO=No higher limit, NI=No information, UN=Unknown, OT=Other

As per the specs (for numerical results only), one of the following needs to be true: 
- Range: Both MODIFIER_LOW and MODIFIER_HIGH contain EQ 
- No upper boundary (e.g. >3):modifier_low = 'GT' or 'GE' and modifier high = NO
- no lower boundary (e.g. <=10): modifier high ='LT' or 'LE' and modifier low = NO

**Comment by burrowse** [comment]
Thanks @writetoritu . I'm wondering if this can be solved with a range low/high operator id ... I will add this to the agenda for the Data Models Group
