### ISSUE TITLE
Lab result - lab name and specimen source

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#42]
Need to add mappings for concept classes : lab name, specimen source, (still looking)

**Comment by writetoritu** [comment]
@toanong is the mapping file you'd sent to me on September 14 2015 complete? 
Is there anything specific you need to discuss with leadership?

**Comment by toanong** [comment]
The mappings for lab_name and specimen_source are NOT complete. Those mappings were added based on the examples provided in the PCORnet V3 specifications document. I'm not sure where to get the complete list of LOINC-concept name and LOINC-specimen source mappings. I wonder if specimen source info is available in the source data, if yes, where to store that info in the PEDSnet CDM. We only need the mappings for these lab names:

A1C=Hemoglobin A1c
CK=Creatine kinase total
CK_MB=Creatine kinase MB
CK_MBI=Creatine kinase MB/creatine kinase total
CREATININE=Creatinine
HGB=Hemoglobin
LDL=Low-density lipoprotein
INR=International normalized ratio
TROP_I=Troponin I cardiac
TROP_T_QL=Troponin T cardiac (qualitative)
TROP_T_QN=Troponin T cardiac (quantitative)

**Comment by mgkahn** [comment]
There is a complete list of lab names/LOINC codes in the PEDSnet CDM documentation somewhere. These codes are PCORnet LOINC codes for PCORnet CDM V3 + additional PEDSnet-specific LOINC codes needed to support the PEDSnet pilot studies.

**Comment by burrowse** [comment]
TODO:
Generate a concept id mapping for the PCORNet Lab Name
Investigation: Need to determine whether or not the LOINC code gives us the specimen source

**Comment by burrowse** [comment]
@baileych What would be a good starting point for the concept mapping for the PCORNet transformation? Also, do we just assume blood as discussed for specimen source? For cultures?

**Comment by baileych** [comment]
OK, here's a mapping for current PCORnet labs:

PEDSnet LOINC | PCORnet Lab Name
--- | ---
4548-4 | A1C
2157-6 | CK
5912-1 | CK_MB? CK_MBI? | Questionable; PEDSnet name is "CPK Isoenzyme", so sites may have interpreted differently
32673-6 | CK_MB
20569-0 | CK_MBI
2160-0 | CREATININE
718-7 | HGB
18262-6 | LDL
2089-1 | LDL
6301-6 | INR
10839-9 | TROP_I
48426-1 | TROP_T_QL
48425-3 | TROP_T_QN

**Comment by writetoritu** [comment]
Charlie suggests using either value for 5912-1 for now. Once we have the data from various sites - we will review this lab (if it exists) and figure out a way to differentiate between CK_MB and CK_MBI.

**Comment by writetoritu** [comment]
In this ETL cycle, we will default specimen source to blood. (until we have a good solution for sites to figure out how to infer specimen source from labs in the EHR data --- to be reviewed further in the next cycle)

**Comment by writetoritu** [comment]
under review https://github.com/PEDSnet/Data_Models/issues/146
