### ISSUE TITLE
Lab result - result qual

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#43]
Result_qual
- Definition: Standardized result for qualitative results. This variable should be NI for quantitative results. Please see the reference tables for additional details and information on acceptable values for each qualitative LAB_NAME.
- predefined value: BORDERLINE, POSITIVE, NEGATIVE, UNDETERMINED, NI=No information, UN=Unknown, OT=Other

Questions
- is this a derived field (all prescribed values have snomed ct code)
- probably we could use value as concept id field for this.
- should we make a convention in pedsnet - (to differentiate result_qual and result_num)
- test on CHOP if it's easier to distinguish between the two (RK to do)

**Comment by burrowse** [comment]
For the question:
should we make a convention in pedsnet - (to differentiate result_qual and result_num)
We can get this from value as number and value as concept

**Comment by burrowse** [comment]
This ETL Cycle: Assert NI for now
Need to determine where the qualitative lab results will be stored 
Proposal come up with standard listing for the value as concept id

**Comment by writetoritu** [comment]
@burrowse just checking if there is an ingoing discussion on this in the data-models space?

**Comment by writetoritu** [comment]
@ChavanShweta please add the following entries to the concept_map.csv file 

```
POSITIVE,Result qualifier,9191,,Positive
NEGATIVE,Result qualifier,9189,,Negative
OT,Result qualifier,0,,Others
OT,Result qualifier,NULL,,Others
```


and make the following changes to the lab_result_cm query 
1. (m8.target_concept,'OT') as result_qual 
2. 	left join dcc_3dot1_pcornet.pedsnet_pcornet_valueset_map m8 on cast(m.value_as_concept_id as text)= m8.source_concept_id and m7.source_concept_class = 'Result qualifier'
