### ISSUE TITLE
Truncated times

### ISSUE THREAD

**Issue by baileych** [PEDSnet/pedsnetcdm_to_pcornetcdm#511]
The conversion of time fields to character values in order to satisfy the PCORnet CDM specification with respect to data type appears to drop a leading or trailing `0`, so that a time of `16:10` translates to `16:1`, and `08:45` translates to `8:45`.

**Comment by burrowse** [comment]
Partially updated in v4.1 Updates https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/pull/515/files

Outstanding columns are:
 - [x] prescribing.rx_order_time
 - [x] lab_result_cm.result_time
 - [x] med_admin.medadmin_start_time
 - [x] med_admin.medadmin_end_time
