### ISSUE TITLE
Encounter raw_payer_name may leak data

### ISSUE THREAD

**Issue by baileych** [PEDSnet/pedsnetcdm_to_pcornetcdm#512]
WIth the expansion of the CDM, the `encounter` table now contains a `raw_payer_name` field, populated by plan names.  As PCORnet has recently stated that they intend to query `raw_` fields on occasion, we should review whether to remove this information, to be compliant with network governance prohibiting release of specific plan names without permission.

**Comment by burrowse** [comment]
Per 5/20 PCORnet Transformation meeting decision was to change the ETL to popular the raw_payer_names with the `plan_class-plan_type` that is being used for the other fields as opposed to sending the visit_payer.plan_name.
