### ISSUE TITLE
Mapping vx_code for immunization table

### ISSUE THREAD

**Issue by piglet25** [PEDSnet/pedsnetcdm_to_pcornetcdm#516]
Here is a list of vaccines found in Seattle's data that are currently **not** mapped:

immunization_source_value
|--|
COVID-19, MRNA, LNP-S, PF, 30 MCG/0.3 ML DOSE
DT VACCINE
DTAP, 5 PERTUSSIS ANTIGENS
DTAP/IPV COMBINED VACCINE
HEP A, ADULT
HPV 9-VALENT
INFLUENZA, HIGH-DOSE, QUADRIVALENT
INFLUENZA, INJECTABLE, MDCK, PF
INFLUENZA, INTRADERMAL, QUADRIVALENT, PF
INFLUENZA, MDCFK, PF, QUADRIVALENT
INFLUENZA, MDCK, QUADRIVALENT, WITH PRESERVATIVE
INFLUENZA, SEASONAL, INJ VACCINE
INFLUENZA, SEASONAL, INJ, PF
MODERNA SARS-COV-2 VACCINATION
PFIZER SARS-COV-2 VACCINATION
TD PRESERVATIVE FREE
YELLOW FEVER - ALT

We either need to map them manually using https://athena.ohdsi.org/search-terms/start or update the approach used.

**Comment by shorrocka** [comment]
https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/commit/3ceb1cad869695ea4231a1099c37e1267191bb64
