### ISSUE TITLE
Add Telehealth removal of discharge date to ETL

### ISSUE THREAD

**Issue by burrowse** [PEDSnet/pedsnetcdm_to_pcornetcdm#527]
During the last ETL cycle, the encounter table was [updated](https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/commit/7335c6dd772361d2b02ce72fc2302dc8a848a533#diff-803e80a46d2cffacce66aaaddd3f17c449143cc88de984519509f955098fa40d) to remove discharge dates from Outpatient visit types.

In PCORnet, outpatient visits are considered to be AV( ambulatory visits), OA (other ambulatory) and TH (Telehealth) visits.

However, in the last ETL cycle, TH was erroneously left out of the ETL update.

The Telehealth concept according to the [ETL Conventions](https://github.com/PEDSnet/Data_Models/blob/master/PEDSnet/docs/PEDSnet_CDM_ETL_Conventions.md#16-visit_occurrence) is `581399`.

The following lines for `discharge_date` and `discharge_time` in PCORnet need to be updated to include the Telehealth concept_id.

https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/1e65215a52311281cb33c850e7f5e1f0597a6136/v4.3_to_v6.0/sql_etl/scripts/etl_scripts/g_encounter.sql#L126

https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/1e65215a52311281cb33c850e7f5e1f0597a6136/v4.3_to_v6.0/sql_etl/scripts/etl_scripts/g_encounter.sql#L132

**Comment by shorrocka** [comment]
This was changed by adding the concept for Telehealth to the removal statement shown above.
This was confirmed by the following query:

select * from test_pcornet.encounter where raw_enc_type = 'Telemedicine'

All records had no discharge dates as desired.
