### ISSUE TITLE
Update/Investigate ETL to remove "bad codes" from procedure table

### ISSUE THREAD

**Issue by burrowse** [PEDSnet/pedsnetcdm_to_pcornetcdm#528]
In the last ETL round, a procedure code for Colorado was flagged during the code_errors run of the DC.

That procedure code was found in `colorado_pcornet.procedures.px=FA`. This occurred from one record and was removed at the time of the DCC.

This should have been accounted for in an ETL update that was made to the transform here:https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/commit/8b4285d184c5c20edead3c92a56a6dffa72b2f0e

Based on the most recent DC run of v4.3 (test submission) this issue was not observed when running the code errors program.

For investigation purposes, we should validate that this issue has been resolved. If so, the issue can be closed.

**Comment by burrowse** [comment]
This should have been accounted for in the last ETL run based on the following commit: https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/commit/8b4285d184c5c20edead3c92a56a6dffa72b2f0e

**Comment by shorrocka** [comment]
After investigating this issue by creating fake records that contain the bad code, I ran the following query to determine if any records with this code were present:
select * from test_pcornet.procedures where px = 'FA'
This was a successful as no records were found and this can be closed.
