### ISSUE TITLE
Revise encounter.facility_type logic to pull forward more granular PEDSnet specialty information

### ISSUE THREAD

**Issue by burrowse** [PEDSnet/pedsnetcdm_to_pcornetcdm#530]
PCORnet has a limited valueset listing for facility_type. We are currently storing a combination of `place_of_service_concept_id` `care_site.specialty_concept_id` and `visit_concept_id` in this field.

Because of the limited valueset, we loose information about the specialty from the incoming PEDSnet data.

As an example, looking for `Nephrology visits` using data created by the v4.2 transform it is impossible as the following query yields: `NI,44814650`

```sql 
select distinct facility_type,raw_facility_type
from chop_pcornet.encounter 
where encounterid::integer in 
(
select visit_occurrence_id
from chop_pedsnet.visit_occurrence vo
inner join chop_pedsnet.care_site cs on vo.care_site_id=cs.care_site_id
where cs.specialty_concept_id in (38004479,45756813));
```

After PCORnet Team discussion, updates would need to be made in the following places:
1. Concept_map csv table...... in anything other than excel :) : https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/v4.3_updates/v4.3_to_v6.0/sql_etl/data/concept_map.csv

Add the following rows:

source_concept_class | target_concept | pcornet_name | source_concept_id | concept_description | value_as_concept_id
-- | -- | -- | -- | -- | --
Facility type | OT | Other | 38004479 | Nephrology |  
Facility type | OT | Other |45756813|Pediatric Nephrology |

*At a minimum for the time being we want to surface the nephrology specialty in a specific way. We would need to do a further evaluation to uncover other specialties that are being masked*

2. Encounter ETL Script

- Adjust ordering of mapping to be m7.target_concept,m6.target_concept,m8.target_concept in the coalesce statements seen below:
https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/1e65215a52311281cb33c850e7f5e1f0597a6136/v4.3_to_v6.0/sql_etl/scripts/etl_scripts/g_encounter.sql#L159
https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/1e65215a52311281cb33c850e7f5e1f0597a6136/v4.3_to_v6.0/sql_etl/scripts/etl_scripts/g_encounter.sql#L162

**Comment by shorrocka** [comment]
This was completed by adding nephrology mapping to other in the mapping table.

This was investigated by looking into the facility type as follows:
![image](https://user-images.githubusercontent.com/89149346/134027745-22ff9494-9a6f-4abb-b4fa-32ee61f930ab.png)
Gathered by this query:
select facility_type, count(*) as num from test_pcornet.encounter group by facility_type;
Showing that nephrology isn't included but can be shown in the NI category.
