### ISSUE TITLE
Update transform to include gestational age as an element in obs_clin

### ISSUE THREAD

**Issue by burrowse** [PEDSnet/pedsnetcdm_to_pcornetcdm#531]
Gestational age is available in the `PEDSnet.person.pn_gestational_age` field.

According to PCORnet, the following are acceptable codes for gestational age:

concept_id|concept_name|concept_code|vocabulary_id|note
---|---|---|---|---
3012266|Gestational age|18185-9|LOINC|Preferred
3001105|Gestational age Estimated from last menstrual period|11885-1|LOINC|
3002209|Gestational age Estimated|11884-4|LOINC|

Because we do not have provenance information for the gestational age, we would need to use the preferred and general code  `3012266  Gestational age 18185-9`.

**Comment by shorrocka** [comment]
This was updated to add the gestational age into obs clin.
This was confirmed by running the following query:
select * from test_pcornet.obs_clin where raw_obsclin_name = 'Gestational age'

Looking at the records to confirm it was added and the correct obsclin code was present.
