### ISSUE TITLE
Update transform to include birth weight as an element in obs_clin

### ISSUE THREAD

**Issue by burrowse** [PEDSnet/pedsnetcdm_to_pcornetcdm#532]
Birth Weight  is available in the `PEDSnet.measurement` table as `measurement_concept_id=3013762` and `measurement_type_concept_id=44818704`.

According to PCORnet, the following are acceptable codes for birth weight:

concept_id|concept_name|concept_code|vocabulary_id|note
---|---|---|---|---
3011043|Birth weight Measured|8339-4 |LOINC|Preferred
40759177|Birth weight - Reported|56056-5|LOINC|Self-reported

Because we do not have provenance information for the birth weight, we would need to use the preferred and general code  `3011043  Birth weight Measured 8339-4`.

**Comment by shorrocka** [comment]
This was successfully completed and the birth weight measure is included in the obsclin table
However there is a lingering quote surrounding the values that were added in. This was resolved by updating the concept map .csv

**Comment by burrowse** [comment]
Thanks @shorrocka !!
