### ISSUE TITLE
Develop code to add census_block_group to OBS_GEN

### ISSUE THREAD

**Issue by burrowse** [PEDSnet/pedsnetcdm_to_pcornetcdm#541]
- Definition:
   - census block group of patient residence
- Source: 
   - `pedsnet.location.census_block_group`
 - Target Table
   -  obs_gen
 - Metadata:
   - `obsgen_type`='LC'
   - `obsgen_code`='49084-7'
   - `obs_gen_result_text`= 'Census block group (2019)'
   - `obsgen_table_modified`='LDS'
   - `obsgen_id_modified`=`addressid` of corresponding record

**Comment by burrowse** [comment]
@shorrocka Thanks for working on this! Is this ready for testing as yet? I see some code added here:
https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/40cd3aa28559c944286b51de08419f09bec03bae/v4.4_to_v6.0/sql_etl/scripts/etl_scripts/n_obs_gen.sql#L196

**Comment by shorrocka** [comment]
Should be ready for testing!

**Comment by shorrocka** [comment]
https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/commit/eea0de7ab22179665c91d0d0370d17ad89950e56

**Comment by shorrocka** [comment]
https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/commit/8406cc8eb5f17a58a0f4fa8800d77166ce55571c

**Comment by burrowse** [comment]
Code updated here: c84c07be1f3d6696f78a6f4dd5625d185613a342
