### ISSUE TITLE
Update lab_result_cm script to assert result_modifier where operator_concept_id is null in PEDSnet

### ISSUE THREAD

**Issue by burrowse** [PEDSnet/pedsnetcdm_to_pcornetcdm#560]
An edit to the following line might be useful:
https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/0f9ed1a0ba7f025b30a42aa90b9a06fd3c1e7002/v4.5_to_v6.0/sql_etl/scripts/etl_scripts/m_lab_result_cm.sql#L43

Things to consider:
- An expansion to the coalesce statement where rslt_modif.target_concept and m.modifier is null
- A derivation based on the pedsnet.value_source_value to assert = as a default where no operands exist

**Comment by boss-sam** [comment]
Change made in V4.5 branch - update.sql file populates any null result modifier with a numerical result with 'EQ'
