### ISSUE TITLE
Encounter: Multiple DRGs violating PK constraint

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#57]
some inpatient visits have two DRGs and it's violating PK constraint of the encounter table. 

the PK field for this table is encounterid (which we are populating using visit_occurrence_id) and each record should have a unique combination of values for (patid, admit_date, providerid, enc_type).  

(based on CHOP data)

As a tentative solution - we are inserting only 1 DRG (minimum value).

**Comment by toanong** [comment]
Can we add DRG code to the unique combination of fields? PCORNet is flexible with the combination of fields used in the PK.

**Comment by writetoritu** [comment]
Also Colorado having multiple discharge disposition for some visits. concept id 44813951

**Comment by writetoritu** [comment]
@toanong Revisiting the discussion on how to capture multiple DRGs/visit in the encounter table. 

The specification states that - "Each record will generally reflect a unique combination of PATID, ADMIT_DATE, PROVIDERID and ENC_TYPE. " So we cannot really modify it. 

Probably, this is another question to ask the PCORnet board.

**Comment by writetoritu** [comment]
@toanong @baileych was this relayed to the PCORnet board?

**Comment by baileych** [comment]
https://github.com/CDMFORUM/CDM-ERRATA/issues/15

**Comment by writetoritu** [comment]
Thank you @baileych !
