### ISSUE TITLE
Vital ETL for the network (6 sites)

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#61]
Beginning Execution of Vital_ETL.sql
SET
ERROR:  duplicate key value violates unique constraint "xpk_vital"
DETAIL:  Key (vitalid)=(--494312088-494312157-) already exists.

**Comment by writetoritu** [comment]
solution: include person_id in the concatenation for PK. 
- tested on the combined dataset. 
- scripts to be updated accordingly.

**Comment by ldavidson** [comment]
This change was merged into the develop branch.

**Comment by writetoritu** [comment]
thanks @ldavidson for testing. I am making this change on another branch "issue-61-vital-pk" as it will be confusing to merge "develop" into "master"
