### ISSUE TITLE
Procedure - pathologic explosion of px values

### ISSUE THREAD

**Issue by baileych** [PEDSnet/pedsnetcdm_to_pcornetcdm#69]
We appear to have an implausibly large number of distinct `px` values in the `pcornet_cdm.procedures` table:

```
=> select count(distinct px) from pcornet_cdm.procedures;
 6008774
=> select count(distinct procedure_source_concept_id) from pedsnet_cdm.procedure_occurrence;
  9559
=> select count(*) from pcornet_cdm.procedures;
 49028003
=> select count(*) from pedsnet_cdm.procedure_occurrence; 
 54276701
=> select count(distinct px) from pcornet_cdm.procedures where px not like 'NM%';
  9549
```

I would have thought the problem was mapping unknown concepts [in the transformation](https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/master/v2%20to%20v3/ETL%20Scripts/Procedure_ETL.sql)
```
case when c.concept_name = 'No matching concept' then
	---- case 2a
	case when m3.source_concept_id IS NOT NULL then split_part(procedure_source_value,'.',1)  
	---- case 2b
	else 'NM'||cast(round(random()*1000000000) as text) end
```
especially given the `NM` prefix, but:
```
=> select count(*) from pedsnet_cdm.procedure_occurrence where procedure_concept_id = 0 and procedure_source_concept_id is null;
     0
```
so it appears that there aren't entries lacking both a mapped and a source concept ID.  The problem appears to be [back in the transformation](https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/master/v2%20to%20v3/ETL%20Scripts/Procedure_ETL.sql), where we join on `m3` to look up a concept ID; `m3` is a mapping for the "administrative" items in the PCORnet CDM:
```
left join pcornet_cdm.cz_omop_pcornet_concept_map m3 on c.vocabulary_id = cast(m3.source_concept_id as text) AND m3.source_concept_class='Procedure Code Type' 
```
Don't we want to join to `c2` instead?
```
left join concept c2 on po.procedure_source_concept_id = c2.concept_id 
```

As an aside, we need to update the comments around the joins as well.  They seem to hint that the joins are doing something else.

@burrowse @toanong

**Comment by toanong** [comment]
@baileych m3 is the mapping for the encoding type of px. The left join to m3 is to make sure that the vocabulary id of the procedure source concept id is among the supported encoding types, namely ICD9CM, ICD10PCS, CPT4, HCPCS, LOINC, NDC and Revenue code. If that's not the case, a random number with the "NM" prefix will be used and the procedure source value will go to raw_px.

Please check if the vocabulary id of the procedure source concept id falls into the list above. 

@burrowse Let me know if you want to meet to resolve this issue.

**Comment by baileych** [comment]
@toanong Sorry,  my goof - wasn't looking carefully enough at the `c.vocabulary_id` in the join condition.  We are generally using the terminologies you mention:
```  
=> select c.vocabulary_id, count(distinct p.procedure_occurrence_id) from pedsnet_cdm.procedure_occurrence p left join pedsnet_cdm.concept c on p.procedure_concept_id = c.concept_id group by c.vocabulary_id;
```

 vocabulary_id  |  count
--------------- | ----------
 Concept Class |     5071
 CPT4          | 44350186
 HCPCS         |   810648
 ICD9Proc      |  2307889
 None          |  6802907

I think the problem may be a leftover from the OMOP v4 to v5 conversion.  The join condition in the transform tries to match the `vocabulary_id` of the procedure source concept to a `source_concept_id` in the mapping table.  But the former is a string in OMOP v5, and the latter is an integer.  So of course no match.

On a (more informed) quick look, here are a couple of Things That Puzzle Charlie:

* the vocabulary_id join.  I think we need to rewrite
```
left join pcornet_cdm.cz_omop_pcornet_concept_map m3 on c.vocabulary_id = cast(m3.source_concept_id as text) AND m3.source_concept_class='Procedure Code Type' 
```
to account for the fact that `c.vocabulary_id` is now a string and won't match a concept ID.

* the parallel joins: `m1` and `m3` appear to be doing the same thing, and `c` and `c2` likewise.  Was the intent that the `c` join clause would be on `po.procedure_concept_id = c.concept_id` and the `c2` be (as both are now written) on `po.procedure_source_concept_id = c.concept_id`?

**Comment by toanong** [comment]
@baileych In the mapping table, source_concept_id (3rd column from the left) of the "Procedure code type" is also string. Sorry about the naming confusion. Orginially, the data in that column were actually numbers, however it's evolved to have text in it also. I noticed that Concept Class, ICD9Proc and None are not in the list of the mapping file. Here's the link to the mapping file:

https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/master/v2%20to%20v3/pedsnet_pcornet_mappings.txt#L82

I can add these to the mapping files, just let me know the PCORnet equivalences. e.g. which PCORnet concept should "None" be mapped to?

About the Things That Puzzle Charlie:

- c and c2 query two different things. c looks for matching concept id in for procedure concept id and c2 
goes after procedure source concept id. However, the code was NOT doing that.
- m1 and m3 finds the matching encoding type for c and c2 respectively.

The script should be corrected as below:

join concept c on po.procedure_concept_id=c.concept_id

AND 

left join pcornet_cdm.cz_omop_pcornet_concept_map m3 on c2.vocabulary_id = cast(m3.source_concept_id as text) AND m3.source_concept_class='Procedure Code Type' 

Thanks for catching these bugs. Let me know if these changes fix the problem.
