### ISSUE TITLE
Death Script needs to be updated for death impute PEDSNet v2.1

### ISSUE THREAD

**Issue by burrowse** [PEDSnet/pedsnetcdm_to_pcornetcdm#70]
The death impute logic needs to be updated now that sites are populating this field for how/if death dates are being imputed:

Insert into pcornet_cdm.death(
	patid, death_date, death_date_impute,
	death_source, death_match_confidence	
)
Select 
	de.person_id as patid,
	de.death_date as death_date,
	***HERE*** `'NI' as death_impute, -- default for now until next ETL cycle` 
	'L' as death_source, --  default for now until next ETL cycle
	null as death_match_confidence --  we do not capture it dicretely in the EHRs 
From
	death de
	join pcornet_cdm.demographic d on d.patid = cast(de.person_id as text)
Where 
	de.death_type_concept_id  = 38003569;

**Comment by writetoritu** [comment]
in the mapping table, can we map "full day imputed" (a possible value in PEDSnet CDM conventions) to "B - both month and day imputed" in PCORnet?

**Comment by burrowse** [comment]
Hi Ritu,

Yes you can. Please see the PEDSNet concept, concept name and the corresponding PCORNet value from the PEDSNet vocabulary.

concept_id |        concept_name        | concept_code 
-----------|----------------------------|--------------
 2000000038 | Full Date Imputed          | FD
 2000000035 | Day imputed                | D
 2000000037 | Not imputed                | N
 2000000034 | Both month and day imputed | B
 2000000036 | Month imputed              | M

**Comment by writetoritu** [comment]
Thanks @burrowse I asked because we dont have any "full date imputed" concept in PCORnet v3.

**Comment by burrowse** [comment]
Okay, 2000000038 should be mapped to B... This concept was created because some of the sites impute the date entirely.

**Comment by toanong** [comment]
@burrowse I'm okay with mapping 2000000038 to B. However, how do you distinguish B (only month and day were imputed) and B (month, day, year imputed) in PCORnet? With this mapping, in PCORnet, it's not safe to assume that whenever you see "B", you at least have the death year right.

**Comment by writetoritu** [comment]
I think Toan is right. Mapping "full date imputed" to "B" implies that the year is not imputed. 
So, we will map "full date imputed" to the OT category in PCORnet. 

I wonder why PCORnet does not have the option for year imputation.

**Comment by burrowse** [comment]
@writetoritu @toanong Okay, I agree with OT
