### ISSUE TITLE
Measurement Script needs to be updated for version 2.1

### ISSUE THREAD

**Issue by burrowse** [PEDSnet/pedsnetcdm_to_pcornetcdm#72]
Multiple issues resolved and columns created in version 2.1 require updates to the measurement script

......
m.measurement_date as lab_order_date, -- default:  populate all dates using the measurement date (only date that we have at the moment)- until new conventions ***HERE***
m.measurement_date as specimen_date,  -- default:  populate all dates using the measurement date (only date that we have at the moment)- until new conventions***HERE***
date_part('hour',m.measurement_time)||':'||date_part('minute',m.measurement_time) as specimen_time, -- HH:MI format 
m.measurement_date as result_date, -- default:  populate all dates using the measurement date (only date that we have at the moment) - until new conventions***HERE***
.........
m.range_low::text as norm_range_low, -- waiting on new conventions 2.1 ***HERE***
null as norm_modifier_low, -- -- waiting on new conventions 2.1 ***HERE***
m.range_high::text as norm_range_high, -- waiting on new conventions 2.1 ***HERE***
null as norm_modifier_high, -- -- waiting on new conventions 2.1 ***HERE***

**Comment by toanong** [comment]
Changes were made to reflect the new conventions. Changes were also made in the pedsnet_pcornet_mappings.xls file. These changes were NOT made in the text and SQL version of that file. Please move the changes before executing the new script.
