### ISSUE TITLE
Measurement Range Values longer than PCORNet Specification

### ISSUE THREAD

**Issue by burrowse** [PEDSnet/pedsnetcdm_to_pcornetcdm#73]
This was seen in the Nemours Data set....the values had to be truncated in the script

***HERE***
left(m.range_low::text,15) as norm_range_low, -- waiting on new conventions 2.1
left(m.range_high::text,15) as norm_range_high, -- waiting on new conventions 2.1

**Comment by aaron0browne** [comment]
I think the PCORnet v3 spec has the length of those fields both at 10, FYI.

**Comment by toanong** [comment]
Thanks @burrowse @aaron0browne . Changes were made.
