### ISSUE TITLE
Vital Script failed for Colorado

### ISSUE THREAD

**Issue by burrowse** [PEDSnet/pedsnetcdm_to_pcornetcdm#74]
ERROR:  duplicate key value violates unique constraint "xpk_vital"
DETAIL:  Key (vitalid)=(3597225-294420349-291935860---) already exists.

Failing rows:

COLORADO

            vitalid             |  patid  | encounterid | measure_date | measure_time | vital_source |       ht       |       wt       | diastolic | systolic | original_bmi | bp_position | tobacco | tobacco_type | smoking | raw_diastolic | raw_systolic | raw_bp_position 
--------------------------------|---------|-------------|--------------|--------------|--------------|----------------|----------------|-----------|----------|--------------|-------------|---------|--------------|---------|---------------|--------------|-----------------
 3597225-294420349-291935860--- | 3597225 | 84169808    | 2015-03-18   | 00:00        | HC           | 65.35436600000 | 180.7788400000 |           |          |              | OT          | OT      | OT           | OT      |               |              | 
 3597225-294420349-291935860--- | 3597225 | 84169808    | 2015-03-18   | 00:00        | HC           | 65.35436600000 | 180.7788400000 |           |          |              | OT          | UN      | OT           | OT      |               |              | 

CHOP

                 vitalid                 |  patid  | encounterid | measure_date | measure_time | vital_source | ht |       wt       | diastolic | systolic  | original_bmi | bp_position | tobacco | tobacco_type | smoking | raw_diastolic | raw_systolic | raw_bp_position 
--------------------------------|---------|-------------|--------------|--------------|--------------|----------------|----------------|-----------|----------|--------------|-------------|---------|--------------|---------|---------------|--------------|-----------------
 4242710--297195695-297195571-297195641- | 4242710 | 109394399   | 2014-06-03   | 18:12        | HC           |    | 191.8019400000 |  54.00000 | 110.00000 |              | OT          | 1       | OT           | OT      | DIASTOLIC     | SYSTOLIC     | 
 4242710--297195695-297195571-297195641- | 4242710 | 109394399   | 2014-06-03   | 18:12        | HC           |    | 191.8019400000 |  54.00000 | 110.00000 |              | OT          | 2       | OT           | OT      | DIASTOLIC     | SYSTOLIC     | 
 4242710--297195695-297195571-297195641- | 4242710 | 109394399   | 2014-06-03   | 18:12        | HC           |    | 191.8019400000 |  54.00000 | 110.00000 |              | OT          | 3       | OT           | OT      | DIASTOLIC     | SYSTOLIC     | 
 4242710--297195695-297195571-297195641- | 4242710 | 109394399   | 2014-06-03   | 18:12        | HC           |    | 191.8019400000 |  54.00000 | 110.00000 |              | OT          | 4       | OT           | OT      | DIASTOLIC     | SYSTOLIC     | 
 4242710--297195695-297195571-297195641- | 4242710 | 109394399   | 2014-06-03   | 18:12        | HC           |    | 191.8019400000 |  54.00000 | 110.00000 |              | OT          | NI      | OT           | OT      | DIASTOLIC     | SYSTOLIC     | 
 4242710--297195695-297195571-297195641- | 4242710 | 109394399   | 2014-06-03   | 18:12        | HC           |    | 191.8019400000 |  54.00000 | 110.00000 |              | OT          | OT      | OT           | OT      | DIASTOLIC     | SYSTOLIC     | 
 4242710--297195695-297195571-297195641- | 4242710 | 109394399   | 2014-06-03   | 18:12        | HC           |    | 191.8019400000 |  54.00000 | 110.00000 |              | OT          | UN      | OT           | OT      | DIASTOLIC     | SYSTOLIC     |

**Comment by toanong** [comment]
@burrowse 
Error was caused my missing systolic and diastolic data in the measurement table. We can try using a sequence for vitalid.  Let me know if it works. Thanks.
