### ISSUE TITLE
populating DRG codes in encounter

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#8]
We are using the observation.value_as_string column (observation_concept_id = 3040464) to populate the encounter.DRG field. The max length of this field is 3 whereas the drg codes are in the following format: "APR7223", "APR1413", "APR1412" and so on. 

action items
- review pcornet conventions 
- discuss with Evy

**Comment by mgkahn** [comment]
MS-DRGs are three digits (see http://www.findacode.com/code-set.php?set=DRG)

What you are seeing are APR-DRG (see http://www.bcbst.com/providers/webinar/APRDRG.pdf) which are much more widely used in pediatrics. The fourth digit is severity, which ranges from 1-4.

But PCORnet only wants MS-DRGs. So the source needs to pull/send the MS-DRG. We (PEDSnet) may want to also capture the APR-DRG but we need to create a  convention for where we would put that additional DRG (probably the usual "observation" bucket).

**Comment by writetoritu** [comment]
@mgkahn thanks for the helpful explanation and the links. I just learnt (from @burrowse ) that we do have a convention to record MS-DRGs: note 1 [here] https://github.com/PEDSnet/Data_Models/blob/master/PEDSnet/V2/docs/Pedsnet_CDM_V2_OMOPV5_ETL_Conventions.md#19-observation-1

I will be making the following changes to the encounter query to get the MS-DRG values. 
- pull from value_as_string where observation_concept_id = 3040464 and observation date occurs after 10/1/2007 , and also join to the concept table to make sure you are getting valid concept ids from value as string (invalid reason is null, concept class id = 'MS-DRG' and vocabualry_id='DRG' )

**Comment by writetoritu** [comment]
need to revise the code to include only the MS-DRGs i.e. where the value_as_concept_id = 0
