### ISSUE TITLE
issues with diagnosis query 

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#82]
Some records (at CHOP and Seattle) with ICD9cm source codes are being recorded as 'OT' dx_type in PCORnet.

**Comment by writetoritu** [comment]
slight edits needed, https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/master/v2%20to%20v3/ETL%20Scripts/Diagnosis_ETL.sql#L34 
use condition_source_concept_id instead of condition_concept_id. 

@toanong do you agree?

**Comment by toanong** [comment]
Was the change because condition_source_concept_id is more complete than condition_concept_id? Keep in mind that condition_concept_id was used to populate dx. So if you make the change, you'll have the change there too.

**Comment by writetoritu** [comment]
HI Toan,

Last year, we had a long discussion on how to populate dx to capture complete information from PEDSnet CDM. 
NOTE: in PEDSnet CDM, condition_concept_id corresponds to SNOMED CT. 
Our decision was motivated by the fact that ICD9 codes are more granular than SNOMEDCT and some ICD9 codes do no have corresponding SNOMED CT codes, and here is what we decided: 
1. Check source vocabulary; if it's one of the PCORnet vocabulary (e.g. ICD9CM) then use condition_source_value. (line 18) 
2. If not, then check the condition_concept_id  (i.e. snomed ct code) and if it's available use it, (line 20) 
3. Else, if no pcornet prescribed vocabulary is available, use a random number of type 'OT' (line 21)

**Comment by toanong** [comment]
I see. I agree with the change. Thanks for reminding me the conventions.
