### ISSUE TITLE
px_source not populated

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#89]
All Sites: Please let us know the source of your procedure data (in general) from the following options: 

1. - OD=Order 
2. - BI=Billing 
3. - CL=Claim, 
4. - NI=No information 
5. - UN=Unknown 
6. - OT=Other

Source of the procedure information. Order and billing pertain to internal healthcare processes and data sources. Claim pertains to data from the bill fulfillment, generally data sources held by insurers and other health plans

**Comment by WustlRob** [comment]
St Louis is getting it's procedure data from billing records (BI=Billing) for both inpatient(hospital) and outpatient(university) EMRs.  I see this is a PEDSnet to PCORnet topic.  Does this answer your question correctly for this forum?

**Comment by jonathan-bickel** [comment]
BCH:   BI

**Comment by writetoritu** [comment]
Thanks @jonathan-bickel @WustlRob yes, this correctly answers the question.

**Comment by burrowse** [comment]
Hi @writetoritu CHOP: OD

**Comment by janetzahner** [comment]
Cincinnati is getting our procedure data from billing (BI).

**Comment by burrowse** [comment]
Summary 
Site | Type
--- |---
Seattle| ?
Boston | BI
CHOP | OD
CCHMC| BI
CO| ?
Nationwide| ?
St Louis| BI
Nemours| ?

**Comment by gmschulte** [comment]
CO : BI

**Comment by dakshar** [comment]
Seattle BI

**Comment by sg0043** [comment]
Nemours: BI

**Comment by burrowse** [comment]
@writetoritu All sites have responded. Can this issue be closed? Do you need more information?

**Comment by writetoritu** [comment]
thanks everyone and @burrowse
