### ISSUE TITLE
Convention to populate Dispensing and Prescribing in PCORnet CDM.

### ISSUE THREAD

**Issue by toanong** [PEDSnet/pedsnetcdm_to_pcornetcdm#90]
The data in the drug_type_concept_id in the Drug Exposure table is the determinant of where records in the Drug Exposure table in PEDSnet CDM are transferred to PCORnet CDM: Dispensing or Prescribing. In current PEDSnet convention, there are three possible concept ids:
- 38000175: Prescription dispensed in pharmacy 
- 38000180: Inpatient administration
- 38000177: Prescription written

The current PEDSnet-PCORnet transformation script only use 2 of the 3 concept ids above to decide which records go to Dispensing and which records go to Prescribing.
- If drug_type_concept_id = 38000175 ==> Dispensing
- If drug_type_concept_id = 38000177 ==> Prescribing

The OMOP-PCORnet CDRN workgroup has recently agreed on a new convention for these two tables.

| Concept Id | Drug Exposure type | Pcornet Table | Prescribing Table Rx Basis |
| --- | --- | --- | --- |
| 38000175 | Prescription dispensed in pharmacy | Dispensing |  |
| 38000176 | Prescription dispensed through mail order | Dispensing |  |
| 38000180 | Inpatient administration | Prescribing | Administration |
| 38000179 | Physician administered drug (identified as procedure) | Prescribing | Administration |
| 43542358 | Physician administered drug (identified from EHR observation) | Prescribing | Administration |
| 43542357 | Physician administered drug (identified from referral record) | Prescribing | Administration |
| 38000177 | Prescription written | Prescribing | Dispensing |

I'm looking to replace the previous convention with new convention. Any objections?

**Comment by writetoritu** [comment]
@toanong Did you get a response on this one? Did we discuss in the data-models workgroup?

**Comment by toanong** [comment]
No I haven't heard anything about this. Should we bring this issue up during the data model group call again?

**Comment by writetoritu** [comment]
Yes sure I will move this issue to the data models repo
