### ISSUE TITLE
Dispensing query

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#92]
Comment by Charlie 
One thing to note: I was looking at Toan/Ritu/PEDSnet’s transformation code for dispensed drugs, and my read is that you’ll end up with correct NDCs iff the source_concept_ids you’re submitting are NDC codes.  That’s not the case, for instance, for CHOP, and I’m not sure why it would be for CHCO.  So I’m inclined to consider it a bug in our PEDSnet-PCORnet transform in the long term, but for the short term I’m writing around it for the med generation — especially since I need to get inpatient meds from the PEDSnet side anyhow.

**Comment by writetoritu** [comment]
@baileych Did you end up re-writing the query? If yes, could you please share with me?

Thanks for finding this bug .

 So we can fix it in the following manner: 
- if source is NDC then forward the concept_code
- else use the concept_id (RxNorm) and determine the mapped NDC code from concept_relationship 
    - is this something that we need to figure out in the data-models workgroup?

**Comment by writetoritu** [comment]
select concept_id_2
from vocabulary.concept_relationship
where relationship_id = 'Maps to'
and concept_id_1 = <concept_id_of_NDC_code>

**Comment by baileych** [comment]
@writetoritu There's a query that should (almost) address this problem in the PMI sprint code, which I hope will be easy to pick up and fit into our transform.

**Comment by writetoritu** [comment]
For: RxNorm -> NDC crosswalk. One drug maps to multiple NDCs, e.g. 40162515 (Acetaminophen 325 MG / Hydrocodone Bitartrate 5 MG Oral Tablet) has 595 NDCs
So using RxNorm codes to determine NDCs may not be feasible; we could probably use RxNorm when there is a single linked NDC?

@toanong Do you know if this was ever discussed in the OMOP-PCORnet sub-committee?

**Comment by writetoritu** [comment]
From Charlie's code: Essentially, if there was an NDC source_concept_id (almost always true), I carried that forward, and if not, I semi-arbitrarily picked the lowest-numbered matching NDC

**Comment by mgkahn** [comment]
Love this heuristic........

**Comment by toanong** [comment]
@writetoritu Interesting convention! The OMOP-PCORnet workgroup has not discussed this issue.
