### ISSUE TITLE
Add site identifiers

### ISSUE THREAD

**Issue by aaron0browne** [PEDSnet/pedsnetcdm_to_pcornetcdm#93]
This will require:

- A change to the DDL for the generated data.
- Several changes to the transformation SQL to pull site IDs from the appropriate columns in the DCC-generated tables (see `site` columns [here](https://github.com/PEDSnet/dcc-loader/blob/master/id-map/id-replacement.sql)).

**Comment by writetoritu** [comment]
@aaron0browne @penningtonj @baileych In addition to the site_id, do we also need to add the "site" column to PCORnet tables?

**Comment by baileych** [comment]
@writetoritu I don't have a specific use case for the text name of the sites, but in general I'd err on the side of inclusion this early in the game.

**Comment by writetoritu** [comment]
@baileych thanks!
